### ISSUE TITLE
cat /dev/urandom holding up test

### ISSUE THREAD

**Issue by NickCody** [cu-ecen-5013/assignment-autotest#23]
This line blocks indefinitely:

https://github.com/cu-ecen-aeld/assignment-autotest/blob/master/test/assignment1/assignment-test.sh#L30

Its causing local tests to block forever and never finish also, the github action is also never finishing, This fix seems to work but I don't have permissions to update this repo:

```bash
dir_name=$(dd bs=30 count=1 status=none if=/dev/urandom | tr -dc 'a-zA-Z0-9')
```

**Comment by dwalkes** [comment]
See https://github.com/cu-ecen-aeld/assignment-autotest/pull/24
