### ISSUE TITLE
Update Sockettest.sh to send multiple packets per connection

### ISSUE THREAD

**Issue by DeekshithPatil** [cu-ecen-5013/assignment-autotest#26]
Created a new branch and started a pull request here: https://github.com/cu-ecen-aeld/assignment-autotest/pull/25

Need to update the script as per Dan's suggestions made on the pull-request.

**Comment by DeekshithPatil** [comment]
Updated branch as per Dan's comments. Ready for review.

**Comment by dwalkes** [comment]
Thanks @DeekshithPatil

I thought we needed changes to the assignment private source code to correctly handle this?  Are these changes on a branch on assignments-complete-private as well?

I'd like to see a passing unit test for a branch on assignments-complete-private with assignment-autotest submodule updated to point to this branch and source code updated to pass this test.
