### ISSUE TITLE
assignment8 instructions confusion

### ISSUE THREAD

**Issue by isch4196** [cu-ecen-5013/assignment-autotest#27]
The instructions in `assignment-autotest/test/assignment8` aren't quite clear.
What I assume to be the correct way to test is to reload the driver each time you run a test.
For example, after running `drivertest.sh`, you would reload the driver and then run `sockettest.sh`.
If the driver isn't reloaded, you end up reading the wrong strings, and therefore fail the test.

I can create a PR to edit the instructions if this is deemed to be an issue.

**Comment by straend** [comment]
That is also what I found out, but then we have problems with the test also. It tries to unload the module while our socket-server is running.

**Comment by isch4196** [comment]
Hi @straend , were you able to figure it out? I think I had the same problem when I was implementing this before, although my memory is a bit hazy. The "troubleshooting" section at the bottom of the assignment 8 instructions should address it: "ensure you are not opening the file descriptor for your driver endpoint from aesdsocket until it is accessed".

**Comment by straend** [comment]
Hi @isch4196, yeah I missed the troubleshooting steps listed there. Thank You for pointing out that.

**Comment by dwalkes** [comment]
Thanks for the feedback, I've updated the assignment 8 instructions to state this in step 5 as well to hopefully make this requirement more clear.
