### ISSUE TITLE
incompatible implicit declaration of built-in function 'strlen' 

### ISSUE THREAD

**Issue by thumbe12856** [cu-ecen-5013/assignment-autotest#31]
Please add   `#include <string.h>` to `assignment-autotest/test/assignment1/username-from-conf-file.h` to avoid incompatible implicit declaration.
```
assignment-autotest/test/assignment1/username-from-conf-file.h:33:36: error: incompatible implicit declaration of built-in function 'strlen' [-Werror]
```

**Comment by thumbe12856** [comment]
You can see the error at https://github.com/cu-ecen-aeld/assignment-1-thumbe12856/actions/runs/7608591563/job/20726756726

**Comment by dwalkes** [comment]
Resolved with https://github.com/cu-ecen-aeld/assignment-autotest/pull/32, thanks!
